project:
  type: website
  output-dir: docs

website:
  title: "travisrutledge"
  navbar:
    right:
      - text: Home 
        href: index.qmd
      - text: About
        href: about.qmd
      - icon: github
        href: https://github.com/travisrutledge
      - icon: linkedin
        href: https://www.linkedin.com/in/travisrutledge/
     
format:
  html:
    theme: sandstone
    css: styles.css

editor: visual